services:
  db: 
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3305:3305"
  redis:
        image: 'redis:5-alpine'
        restart: always
        ports:
            - "6380:6379"
  app: 
        build: .
        command: bash -c "bash ./init.sh"
        volumes: 
            - ".:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
            - redis
            - elasticsearch
        restart: always
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis://localhost:6379/1
            ES_HOST: elasticsearch
  elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
          - xpack.security.enabled=false
          - "discovery.type=single-node"
        ports:
          - 9200:9200
 
